### ISSUE TITLE
Implement Audit Punishment

### ISSUE THREAD

**Issue by kushk2** [ADimoska/SOMASExtended#110]
Currently in the event of a successful audit, nothing happens, even though this is passed through to the agents. The server should execute logic upon a successful audit to do with the culprit. This logic should be in the AoA.

**Comment by kushk2** [comment]
Sounds good @arnavxkohli , let's leave it up to teams to implement specific punishments. Should we add template code for them to fill in/override? For example @EXiao3's implementation ?

**Comment by arnavxkohli** [comment]
Yeah I think a helper would be nice. Like how much of the agent's current score (in %) is being taken from them? Do you think you can re-work your code to do that? @EXiao3 I assume it already puts this back into that team's common pool
