### ISSUE TITLE
Remove Agent from associated `Team` struct when dead

### ISSUE THREAD

**Issue by kushk2** [ADimoska/SOMASExtended#21]
## Error Description

Main branch fails to run. 

Error is in `AllocateAoAs` and happens because agents are being iterated over via their respective `teams` - however, they may be dead but still in a team. Therefore calling the function on dead agents which references a null pointer (to the agent).

```
[se`ver] New round score threshold: 11
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x68 pc=0x10081d380]

goroutine 1 [running]:
SOMAS_Extended/server.(*EnvironmentServer).AllocateAoAs(0x14000114000)
        /Users/kush/Documents/Imperial/Year4/SOMAS/SOMASExtended/server/EnvironmentServer.go:79 +0x130
SOMAS_Extended/server.(*EnvironmentServer).RunStartOfIteration(0x14000114000, 0x100880c00?)
        /Users/kush/Documents/Imperial/Year4/SOMAS/SOMASExtended/server/EnvironmentServer.go:67 +0x7c
github.com/MattSScott/basePlatformSOMAS/v2/pkg/server.(*BaseServer[...]).Start(0x100880c00)
        /Users/kush/go/pkg/mod/github.com/!matt!s!scott/base!platform!s!o!m!a!s/v2@v2.1.0/pkg/server/baseServer.go:108 +0x80
SOMAS_Extended/server.(*EnvironmentServer).Start(...)
        /Users/kush/Documents/Imperial/Year4/SOMAS/SOMASExtended/server/EnvironmentServer.go:107
main.main()
        /Users/kush/Documents/Imperial/Year4/SOMAS/SOMASExtended/main.go:25 +0x90
```

## Fix Should

- Remove Agents from the respective `Team` struct upon death
- Ensure agent is not in server's `deadAgent` map (see `runTurn` for similar already implemented)
- Ensure that the last agent that a team was associated with remains in the agent's own data/structure, so that we can still associate them with the team in case they win (but died in the progress)

**Comment by kishan-v** [comment]
I believe this issue isn’t quite resolved yet. We saw another occurrence in #52

**Comment by arnavxkohli** [comment]
Should be resolved by #68

**Comment by kishan-v** [comment]
Has this issue been resolved now?

**Comment by Somewheref** [comment]
> Has this issue been resolved now?

I believe it should, as in my visualization #89 I have plotted all agent death events and stuff which all seems correct, and main.go runs pretty smoothly. 

I will mark this as closed for now :)
