### ISSUE TITLE
AoA tied vote

### ISSUE THREAD

**Issue by EXiao3** [ADimoska/SOMASExtended#25]
Work on allocate AoA vote function for when max vote is tied. Implement some sort of logic based off on lectures. 

_Depends on #9_

**Comment by arnavxkohli** [comment]
Not sure if this is till open, but if it is, it's probably best to have this be allotted randomly in case of a tie. More complicated logic could be an extension.

**Comment by arnavxkohli** [comment]
Has this been resolved?
