### ISSUE TITLE
Agents leaving voluntarily/being kicked out 

### ISSUE THREAD

**Issue by kishan-v** [ADimoska/SOMASExtended#26]

**Comment by vedantvasugupta** [comment]
When do we want to ask the agents if they want to leave?

**Comment by kishan-v** [comment]
> When do we want to ask the agents if they want to leave?

If I'm not wrong, they're given the opportunity once per turn, and they may only do so at the end?
It cannot be before a possible punishment due to withdrawal audit.

Maybe they can have another, earlier opportunity to leave after the point where a punishment would take place for the contribution audit?

**Comment by johanjino** [comment]
I agree, end of each round makes sense. That means after everything for that round has completed.

**Comment by arnavxkohli** [comment]
Are we leaving the being kicked out up to the individual AoAs? We probably need some voting in such a case right?
