### ISSUE TITLE
Move Server Audit Functions from Team struct to AoA struct

### ISSUE THREAD

**Issue by kishan-v** [ADimoska/SOMASExtended#29]
This will allow each AoA definition to override the audit functions (within the type signature constraints that will need to be defined in `IArticlesOfAssociation`) that will be called each turn, and [when an audit is carried out (after a successful vote)](https://github.com/ADimoska/SOMASExtended/issues/9).

**Comment by arnavxkohli** [comment]
See https://github.com/ADimoska/SOMASExtended/pull/30
