### ISSUE TITLE
Fix function override for child classes of ExtendedAgent

### ISSUE THREAD

**Issue by harryknee** [ADimoska/SOMASExtended#36]
### Issue
Currently when you create a child class of ExtendedAgent and override a function, the base class implementation is always called. An example of this case can be found [here](https://go.dev/play/p/uNDuQAJM5wU). 

This happens whenever you try to call an overridden function from a function that is only defined in base struct (stage rule function like `RunTurn()`, which we want to keep fixed across teams). Since the overridden function is called _indirectly_ inside the stage rule function, the struct cannot see that the function is overridden in the base stage rule, unless an interface instance is passed as a parameter.

### Solution
The fix for this is that each agent needs to know the specific composition (different for each team's agent) of the ExtendedAgent implementation. This can be done via passing an additional parameter (interface), and another way is to store an interface instance at construction. An example showing how both works can be found [here](https://go.dev/play/p/6eZUaWACnNu).

### Rule-of-thumb for polymorphism in ExtendedAgent
When each team implement their own strategic functions, they should just simply override certain functions from the ExtendedAgent. We need to make sure the correct corresponding function will be called automatically via function override, on the correct instance.

The general rule-of-thumb to make sure polymorphism for the ExtendedAgent child class to work is:
1. Function that can be overridden (i.e. strategies) must be included in the IExtendedAgent interface
2. Calling function that shouldn't be overridden in ExtendedAgent should use `mi.BaseFunction()`, so we ensure the base implementation is used

Implementation that passes additional parameter requires:
1. Function that calls overridable functions needs an extra parameter of interface type `IExtendedAgent` (e.g. `StartRollingDice(instance common.IExtendedAgent)`)
2. Calling overridable functions in ExtendedAgent should use `instance.OverridenFunction()`, on the parameter passed in

Another implementation by storing the instance:
1. Update ExtendedAgent to have an extra field `Instance`
2. Create a constructor function with `Instance : nil`, and then overwrite the instance with itself
3. Calling overridable functions in ExtendedAgent should use `mi.Instance.OverridenFunction()`

**Comment by kishan-v** [comment]
Note that the [current](https://github.com/ADimoska/SOMASExtended/commit/ece782e13023800090d0591f7a37a30fe2afea03) implementation of `RunTurn()` **correctly** calls the overridden implementation of the agent functions since the Agent map stores the agents as the `IExtendedAgent` interface type, so no changes are required in that function.

By storing agents in `agentMap` as the interface type, we ensure that method calls are dynamically dispatched based on the actual concrete type of the agent.

**Comment by harryknee** [comment]
> Note that the [current](https://github.com/ADimoska/SOMASExtended/commit/ece782e13023800090d0591f7a37a30fe2afea03) implementation of `RunTurn()` **correctly** calls the overridden implementation of the agent functions since the Agent map stores the agents as the `IExtendedAgent` interface type, so no changes are required in _that_ function.
> 
> By storing agents in `agentMap` as the interface type, we ensure that method calls are dynamically dispatched based on the actual concrete type of the agent.

I think it still doesn't work as expected, because Golang doesn't really have a full dynamic dispatch. 

I am taking the example of dice roll action. It works as intended when you override the entire `StartRollingDice()`, but I don't think we want to do that as the dice rolling game rule should be made fixed for all teams (we shouldn't allow this to be overridden). From my understanding, each team only needs to override `StickOrAgain()` function to decide whether to stick or roll again, which is called inside `StartRollingDice()`. This same override issue occurs whenever you try to call an overridden function from a function defined in base class. In this case, trying to call overridden `StickOrAgain()` from `StartRollingDice()` of ExtendedAgent.

When I override StickOrAgain(), the base StickOrAgain() is still called since it is **indirectly** called:
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/9dc85c7f-0976-4eb8-95f2-b3315b2b2c4c">
Only when I override StartRollingDice() works, because it is called **directly** in the RunTurn():
<img width="996" alt="image" src="https://github.com/user-attachments/assets/1584d23a-caca-4a95-95ec-f43a11087c32">

**Comment by ajanthan-k** [comment]
How about adding just:

```go
func (mi *ExtendedAgent) GetSelf() common.IExtendedAgent {
	return mi.BaseAgent.AccessAgentByID(mi.GetID())
}
```

and then doing:

```go
func (mi *ExtendedAgent) StartRollingDice() {
    agent := mi.GetSelf()
    ....
        willStick = agent.StickOrAgain()
    ...
```

Seemed to work when I tried it, but haven't tested it properly
