### ISSUE TITLE
Nil pointer dereference when trying to kill agent

### ISSUE THREAD

**Issue by kishan-v** [ADimoska/SOMASExtended#52]
Hey guys, one of our runs hit the following error
 
 ```panic: runtime error: invalid memory address or nil pointer dereference```
 
 Wondering if it's the same issue you guys were looking into? @nlewxxs @blayney 
 
 It doesn't happen every time due to the game's randomness so it is hard to reproduce when debugging locally.
 
 Console output:
[somas-segfault-28-11-24.txt](https://github.com/user-attachments/files/17952264/somas-segfault-28-11-24.txt)

_Originally posted by @kishan-v in https://github.com/ADimoska/SOMASExtended/issues/38#issuecomment-2506743550_

**Comment by Somewheref** [comment]
just about to say it, seems like a probabilistic bug

**Comment by vedantvasugupta** [comment]
Hey everyone,

Just wanted to give a quick update: I found the panic happens when `KillAgent` tries to remove an agent that's not part of any team. I'm working on a fix to handle agents without a team properly when they're killed.

**Comment by Somewheref** [comment]
> Hey everyone,
> 
> Just wanted to give a quick update: I found the panic happens when `KillAgent` tries to remove an agent that's not part of any team. I'm working on a fix to handle agents without a team properly when they're killed.

I also noticed it and fixed it in #89 , so I will close this issue
