### ISSUE TITLE
Move Roll Decision to the server

### ISSUE THREAD

**Issue by arnavxkohli** [ADimoska/SOMASExtended#58]
I believe the power to roll and query for rolls should be moved to the server, because this would allow it more control over who is making decisions for whom. Jeremy seems to love the idea of other agents deciding if one agent is going to roll or not. In a complete egalitarian democracy and for various other AoAs this could be a good QoL feature in general.

Related to https://github.com/ADimoska/SOMASExtended/issues/33

**Comment by dhruvds12** [comment]
This is not MVP, moved to extension milestone. I think this low priority considering we still are far from MVP. Good idea though.

**Comment by arnavxkohli** [comment]
Agreed
