### ISSUE TITLE
Fix Broadcast Stated Contributions to agents in team

### ISSUE THREAD

**Issue by kishan-v** [ADimoska/SOMASExtended#63]
- Broadcast (sync) stated contributions (int) to other members of your team
  - Should be called after the contributions are made but before contribution audit
  - Fix message contents e.g. no need to broadcast expected contribution(?)
- Receive stated contribution (int) messages (must happen before contribution audit)
  - Can leave further implementation of the data structure and logic to store these messages up to each derived agent, but at least have print statements to show the message being received

Note: some of the messaging functionality for this has already been implemented

**Comment by arnavxkohli** [comment]
Does this need to happen for withdrawals too?

**Comment by arnavxkohli** [comment]
(Hopefully) #66 provides a baseline to address this :)
