### ISSUE TITLE
Add global `auditCost` system

### ISSUE THREAD

**Issue by kushk2** [ADimoska/SOMASExtended#74]
## Description 

As per Friday 29th(?) class meeting, this cost to audit **must** be constant for all groups.  It can be a (linearly for now) scaling system of audit success such that:

- An audit cost of `1` results in a `10%` chance of `audit(agent1)` returning `True` when they did actually cheat. I think in this case we need to consider whether we want to: return `auditUnsuccessful` which should be a similar error report method to a a failure to audit due to lack of common pool resources, OR, return `False`. I believe that `False` is slightly misleading as it is telling all agents that `agent1` DID NOT LIE, when they might've, just that the server did not catch them.

## Suggested Implementation changes

- Add a function that, when called with a cost input (between 1 and 10) returns the probability of success. e.g. `calculateAuditLikelihood`
- Use this function when seeing if the audit was successful or not, and therefore can/cant proceed. e.g `auditWasSuccessful`
- Use this function when auditing as a check before main audit logic, such that `audit(agent1)` returns `AuditUnsuccessful` with a probability of `calculateAuditLikelihood`, using `auditWasSuccessful` as a helper. 
- Update agents so that they can handle this failure, and so that is treated differently to a `True` or `False` output. This should be similar to already implemented logic for insufficient common pool resources to carry out an audit

**Comment by arnavxkohli** [comment]
Maybe instead of a probability based system, we could use a queue based on the cost to audit. This would be more reliable (so have a longer memory) if we pay more to audit vs it could have a shorter memory (less reliable) if we pay less. Can be dynamically adjusted. Team 2 already has an implementation for this @kushk2. If you want I can move it to the main server.

**Comment by kushk2** [comment]
I'm ok with this implementation as an alternative - but not sure it is congruent with what Jeremy/Matt have been saying. It is worth asking them before we go ahead with developing any new infrastructure/features for this ticket.

**Comment by johanjino** [comment]
Having dynamic memory for different cost is good. I dont think thats is what Jeremy suggested, but I think we can get away with that.

**Comment by arnavxkohli** [comment]
I think this is a bit more nuanced than a simple binary value as well. If we are using a probability distribution, what are we doing in case there are multiple infractions within one audit? Maybe it could either return the number of infractions or be unsuccessful as you mentioned.

**Comment by arnavxkohli** [comment]
Also just got the A-OK from Matt :) @kushk2 @johanjino 
<img width="898" alt="image" src="https://github.com/user-attachments/assets/ee4f88f8-3506-49d8-832d-95cbe4011c1b">

**Comment by kushk2** [comment]
nice, thanks for that arnav - feel free to submit MR of your guys' stuff into main

**Comment by arnavxkohli** [comment]
Just trying to tweak it so that it works for everyone, may need some refactoring from the individual teams. I will try to keep it as similar as possible to the old design

**Comment by johanjino** [comment]
great, good work! Hopefully we can write something that doesnt break anything else
