### ISSUE TITLE
Finishing up data visualization

### ISSUE THREAD

**Issue by Somewheref** [ADimoska/SOMASExtended#92]
Following #89, I will finish up the bugs and try to add all necessary data for visualization.

- overlay threshold on agent score graph
- fix **contribution** value bug
- add bar 3d chart for **team common pool values**
- add various other data (aoa used etc) as text

Finger crossed we can finish all before deadline 🙏

**Comment by Somewheref** [comment]
Also, probably going to add a function that can export the data file. This way you can use it in your report and stuff I think.

**Comment by kishan-v** [comment]
These features are awesome, thanks for adding them @Somewheref

**Comment by johanjino** [comment]
This will be amazing!

**Comment by Somewheref** [comment]
I found it really hard to plot pretty data in go package... have switched to python and is a lot easier.

Only downside is that it requires some packages. But plotting is not an essential part of game flow, so only the person who want to use python to plot needs to install the necessary packages.
